source "https://rubygems.org"

# Lock to GitHub Pages environment for parity with production
# See: https://pages.github.com/versions/

gem "github-pages", group: :jekyll_plugins

gem "webrick", "~> 1.8"
